// Place fonts/icomoon.ttf in your fonts/ directory and
// add the following to your pubspec.yaml
// flutter:
//   fonts:
//    - family: icomoon
//      fonts:
//       - asset: fonts/icomoon.ttf
import 'package:flutter/widgets.dart';

class Icomoon {
  Icomoon._();

  static const String _fontFamily = 'icomoon';

  static const IconData phNotePencilLight = IconData(0xe900, fontFamily: _fontFamily);
  static const IconData phPenLight = IconData(0xe901, fontFamily: _fontFamily);
  static const IconData phPencilSimpleLight = IconData(0xe902, fontFamily: _fontFamily);
  static const IconData phSignInLight = IconData(0xe903, fontFamily: _fontFamily);
  static const IconData phInfoLight = IconData(0xe904, fontFamily: _fontFamily);
  static const IconData phCurrencyEurLight = IconData(0xe905, fontFamily: _fontFamily);
  static const IconData phPlusCircleLight2 = IconData(0xe906, fontFamily: _fontFamily);
  static const IconData phPlusCircleLight = IconData(0xe907, fontFamily: _fontFamily);
  static const IconData phPlusLight = IconData(0xe908, fontFamily: _fontFamily);
  static const IconData phPlusSquareLight = IconData(0xe909, fontFamily: _fontFamily);
  static const IconData phCheckSquareLight2 = IconData(0xe90a, fontFamily: _fontFamily);
  static const IconData phBatteryPlusLight = IconData(0xe90b, fontFamily: _fontFamily);
  static const IconData phBatteryPlusVerticalLight = IconData(0xe90c, fontFamily: _fontFamily);
  static const IconData phAddressBookLight2 = IconData(0xe90d, fontFamily: _fontFamily);
  static const IconData phAddressBookLight = IconData(0xe90e, fontFamily: _fontFamily);
  static const IconData phAlarmLight2 = IconData(0xe90f, fontFamily: _fontFamily);
  static const IconData phAlarmLight = IconData(0xe910, fontFamily: _fontFamily);
  static const IconData phAppleLogoLight2 = IconData(0xe911, fontFamily: _fontFamily);
  static const IconData phAppleLogoLight = IconData(0xe912, fontFamily: _fontFamily);
  static const IconData phArrowCircleLeftLight2 = IconData(0xe913, fontFamily: _fontFamily);
  static const IconData phArrowCircleRightLight2 = IconData(0xe914, fontFamily: _fontFamily);
  static const IconData phArrowCircleLeftLight = IconData(0xe915, fontFamily: _fontFamily);
  static const IconData phArrowCircleRightLight = IconData(0xe916, fontFamily: _fontFamily);
  static const IconData phBellLight2 = IconData(0xe917, fontFamily: _fontFamily);
  static const IconData phBellLight = IconData(0xe918, fontFamily: _fontFamily);
  static const IconData phBellRingingLight3 = IconData(0xe919, fontFamily: _fontFamily);
  static const IconData phBellRingingLight = IconData(0xe91a, fontFamily: _fontFamily);
  static const IconData phBrowsersLight = IconData(0xe91b, fontFamily: _fontFamily);
  static const IconData phCalendarBlankLight2 = IconData(0xe91c, fontFamily: _fontFamily);
  static const IconData phCalendarDotsLight2 = IconData(0xe91d, fontFamily: _fontFamily);
  static const IconData phCalendarDotsLight = IconData(0xe91e, fontFamily: _fontFamily);
  static const IconData phCalendarHeartLight2 = IconData(0xe91f, fontFamily: _fontFamily);
  static const IconData phCalendarStarLight2 = IconData(0xe920, fontFamily: _fontFamily);
  static const IconData phCalendarHeartLight = IconData(0xe921, fontFamily: _fontFamily);
  static const IconData phCalendarStarLight = IconData(0xe922, fontFamily: _fontFamily);
  static const IconData phCameraPlusLight2 = IconData(0xe923, fontFamily: _fontFamily);
  static const IconData phCameraPlusLight = IconData(0xe924, fontFamily: _fontFamily);
  static const IconData phChatCircleDotsLight2 = IconData(0xe925, fontFamily: _fontFamily);
  static const IconData phChatCircleDotsLight3 = IconData(0xe926, fontFamily: _fontFamily);
  static const IconData phChatCircleTextLight2 = IconData(0xe927, fontFamily: _fontFamily);
  static const IconData phChatCircleTextLight = IconData(0xe928, fontFamily: _fontFamily);
  static const IconData phCheckCircleLight2 = IconData(0xe929, fontFamily: _fontFamily);
  static const IconData phCheckCircleLight = IconData(0xe92a, fontFamily: _fontFamily);
  static const IconData phCheckSquareLight21 = IconData(0xe92b, fontFamily: _fontFamily);
  static const IconData phCheckSquareLight = IconData(0xe92c, fontFamily: _fontFamily);
  static const IconData phChecksLight2 = IconData(0xe92d, fontFamily: _fontFamily);
  static const IconData phChecksLight = IconData(0xe92e, fontFamily: _fontFamily);
  static const IconData phDotsThreeOutlineLight2 = IconData(0xe92f, fontFamily: _fontFamily);
  static const IconData phDotsThreeOutlineLight = IconData(0xe930, fontFamily: _fontFamily);
  static const IconData phDownloadSimpleLight2 = IconData(0xe931, fontFamily: _fontFamily);
  static const IconData phDownloadSimpleLight = IconData(0xe932, fontFamily: _fontFamily);
  static const IconData phEnvelopeSimpleLight = IconData(0xe933, fontFamily: _fontFamily);
  static const IconData phEyeClosedLight = IconData(0xe934, fontFamily: _fontFamily);
  static const IconData phFacebookLogoLight2 = IconData(0xe935, fontFamily: _fontFamily);
  static const IconData phEyeLight = IconData(0xe936, fontFamily: _fontFamily);
  static const IconData phFacebookLogoLight = IconData(0xe937, fontFamily: _fontFamily);
  static const IconData phFingerprintSimpleLight = IconData(0xe938, fontFamily: _fontFamily);
  static const IconData phFlowerLight = IconData(0xe939, fontFamily: _fontFamily);
  static const IconData phFireSimpleLight = IconData(0xe93a, fontFamily: _fontFamily);
  static const IconData phFlowerLotusLight = IconData(0xe93b, fontFamily: _fontFamily);
  static const IconData phGiftLight = IconData(0xe93c, fontFamily: _fontFamily);
  static const IconData phGoogleLogoLight2 = IconData(0xe93d, fontFamily: _fontFamily);
  static const IconData phGoogleLogoLight = IconData(0xe93e, fontFamily: _fontFamily);
  static const IconData phHeartLight2 = IconData(0xe93f, fontFamily: _fontFamily);
  static const IconData phHeartLight = IconData(0xe940, fontFamily: _fontFamily);
  static const IconData phHouseLight = IconData(0xe941, fontFamily: _fontFamily);
  static const IconData phIdentificationBadgeLight2 = IconData(0xe942, fontFamily: _fontFamily);
  static const IconData phInstagramLogoLight2 = IconData(0xe943, fontFamily: _fontFamily);
  static const IconData phInstagramLogoLight = IconData(0xe944, fontFamily: _fontFamily);
  static const IconData phIdentificationBadgeLight = IconData(0xe945, fontFamily: _fontFamily);
  static const IconData phKeyLight2 = IconData(0xe946, fontFamily: _fontFamily);
  static const IconData phKeyLight = IconData(0xe947, fontFamily: _fontFamily);
  static const IconData phLinkSimpleHorizontalLight = IconData(0xe948, fontFamily: _fontFamily);
  static const IconData phLinktreeLogoLight = IconData(0xe949, fontFamily: _fontFamily);
  static const IconData phListStarLight = IconData(0xe94a, fontFamily: _fontFamily);
  static const IconData phListHeartLight = IconData(0xe94b, fontFamily: _fontFamily);
  static const IconData phMagicWandLight = IconData(0xe94c, fontFamily: _fontFamily);
  static const IconData phMailboxLight2 = IconData(0xe94d, fontFamily: _fontFamily);
  static const IconData phMailboxLight = IconData(0xe94e, fontFamily: _fontFamily);
  static const IconData phMapPinLineLight2 = IconData(0xe94f, fontFamily: _fontFamily);
  static const IconData phMapPinLineLight = IconData(0xe950, fontFamily: _fontFamily);
  static const IconData phMapPinSimpleAreaLight = IconData(0xe951, fontFamily: _fontFamily);
  static const IconData phMaskHappyLight = IconData(0xe952, fontFamily: _fontFamily);
  static const IconData phMedalLight = IconData(0xe953, fontFamily: _fontFamily);
  static const IconData phMegaphoneLight = IconData(0xe954, fontFamily: _fontFamily);
  static const IconData phMicrophoneLight = IconData(0xe955, fontFamily: _fontFamily);
  static const IconData phMoonLight = IconData(0xe956, fontFamily: _fontFamily);
  static const IconData phMoonStarsLight = IconData(0xe957, fontFamily: _fontFamily);
  static const IconData phMusicNotesSimpleLight = IconData(0xe958, fontFamily: _fontFamily);
  static const IconData phPaperPlaneRightLight2 = IconData(0xe959, fontFamily: _fontFamily);
  static const IconData phPaperPlaneRightLight = IconData(0xe95a, fontFamily: _fontFamily);
  static const IconData phPlantLight = IconData(0xe95b, fontFamily: _fontFamily);
  static const IconData phPlusCircleLight21 = IconData(0xe95c, fontFamily: _fontFamily);
  static const IconData phPlusCircleLight1 = IconData(0xe95d, fontFamily: _fontFamily);
  static const IconData phSealLight = IconData(0xe95e, fontFamily: _fontFamily);
  static const IconData phSirenLight = IconData(0xe95f, fontFamily: _fontFamily);
  static const IconData phSmileyLight = IconData(0xe960, fontFamily: _fontFamily);
  static const IconData phShootingStarLight = IconData(0xe961, fontFamily: _fontFamily);
  static const IconData phSmileyMehLight = IconData(0xe962, fontFamily: _fontFamily);
  static const IconData phSmileySadLight = IconData(0xe963, fontFamily: _fontFamily);
  static const IconData phSparkleLight = IconData(0xe964, fontFamily: _fontFamily);
  static const IconData phSpeakerNoneLight = IconData(0xe965, fontFamily: _fontFamily);
  static const IconData phSunDimLight = IconData(0xe966, fontFamily: _fontFamily);
  static const IconData phStarAndCrescentLight = IconData(0xe967, fontFamily: _fontFamily);
  static const IconData phSunHorizonLight2 = IconData(0xe968, fontFamily: _fontFamily);
  static const IconData phSunHorizonLight = IconData(0xe969, fontFamily: _fontFamily);
  static const IconData phTimerLight = IconData(0xe96a, fontFamily: _fontFamily);
  static const IconData phTrashLight2 = IconData(0xe96b, fontFamily: _fontFamily);
  static const IconData phTrashLight = IconData(0xe96c, fontFamily: _fontFamily);
  static const IconData phUserCheckLight2 = IconData(0xe96d, fontFamily: _fontFamily);
  static const IconData phUser2 = IconData(0xe96e, fontFamily: _fontFamily);
  static const IconData phUserCheckLight = IconData(0xe96f, fontFamily: _fontFamily);
  static const IconData phUserCircleCheckLight2 = IconData(0xe970, fontFamily: _fontFamily);
  static const IconData phUserCircleCheckLight = IconData(0xe971, fontFamily: _fontFamily);
  static const IconData phUserListLight2 = IconData(0xe972, fontFamily: _fontFamily);
  static const IconData phUserListLight = IconData(0xe973, fontFamily: _fontFamily);
  static const IconData phUser = IconData(0xe974, fontFamily: _fontFamily);
  static const IconData phUsersFourLight2 = IconData(0xe975, fontFamily: _fontFamily);
  static const IconData phUsersFourLight = IconData(0xe976, fontFamily: _fontFamily);
  static const IconData phWarningCircleLight2 = IconData(0xe977, fontFamily: _fontFamily);
  static const IconData phWarningCircleLight = IconData(0xe978, fontFamily: _fontFamily);
  static const IconData phWechatLogoLight2 = IconData(0xe979, fontFamily: _fontFamily);
  static const IconData phWechatLogoLight = IconData(0xe97a, fontFamily: _fontFamily);
  static const IconData phWhatsappLogoLight = IconData(0xe97b, fontFamily: _fontFamily);
  static const IconData phWhatsappLogoLight2 = IconData(0xe97c, fontFamily: _fontFamily);
  static const IconData phXCircleLight2 = IconData(0xe97d, fontFamily: _fontFamily);
  static const IconData phXCircleLight = IconData(0xe97e, fontFamily: _fontFamily);
  static const IconData phYinYangFill = IconData(0xe97f, fontFamily: _fontFamily);
  static const IconData phYinYangLight = IconData(0xe980, fontFamily: _fontFamily);
}
